version: "3.9"

services:
  servidor:
    build:
      context: ./servidor
      dockerfile: dockerfile.api
    container_name: servidor
    volumes:
      - servidor_data:/data
    networks:
      redp2p:
        ipv4_address: 172.28.0.2
    environment:
      - SERVER_URL=http://172.28.0.2:8000
    ports:
      - "8000:8000"   # expone la API en tu máquina host

  P1:
    build:
      context: ./peer
      dockerfile: dockerfile.peer
    container_name: P1
    volumes:
      - p1_data:/data
    networks:
      redp2p:
        ipv4_address: 172.28.0.3
    environment:
      - PEER_NAME=Peer1
      - PEER_PASSWORD=sd1234
      - PEER_URL=http://172.28.0.3:8001
      - PEER_PORT=8001
      - API_URL=http://172.28.0.2:8000/login
      - AUTH_ENABLED=true
    ports:
      - "8001:8001"

  P2:
    build:
      context: ./peer
      dockerfile: dockerfile.peer
    container_name: P2
    volumes:
      - p2_data:/data
    networks:
      redp2p:
        ipv4_address: 172.28.0.4
    environment:
      - PEER_NAME=Peer2
      - PEER_PASSWORD=sd1234
      - PEER_URL=http://172.28.0.4:8002
      - PEER_PORT=8002
      - API_URL=http://172.28.0.2:8000/login
      - AUTH_ENABLED=true
    ports:
      - "8002:8002"

  P3:
    build:
      context: ./peer
      dockerfile: dockerfile.peer
    container_name: P3
    volumes:
      - p3_data:/data
    networks:
      redp2p:
        ipv4_address: 172.28.0.5
    environment:
      - PEER_NAME=Peer3
      - PEER_PASSWORD=sd1234
      - PEER_URL=http://172.28.0.5:8003
      - PEER_PORT=8003
      - API_URL=http://172.28.0.2:8000/login
      - AUTH_ENABLED=true
    ports:
      - "8003:8003"

networks:
  redp2p:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  servidor_data:
  p1_data:
  p2_data:
  p3_data:
